services:

  _defaults:
    public: false
    autowire: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\:
    resource: '*'

  # Factories

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Factory\PostFactory:
    public: true


  # Services

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Shared\Adapter\AdapterInterface:
    class: Ramsterhad\DeepDanbooruTagAssist\Application\Api\Shared\Adapter\CurlAdapter
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\AuthenticationService:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\EndpointUrlService:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\PushTagsService:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\RequestTagService:
    public: true

  Ramsterhad\DeepDanbooruTagAssist\Application\Api\Danbooru\Service\RequestPostService:
    public: true